### ISSUE TITLE
[request] add aiocircuitbreaker to Conda-forge

### ISSUE THREAD

**Issue by maximskorik** [sgenya/aiocircuitbreaker#4]
Hi @sgenya, we'd like to use **aiocircuitbreaker** in https://github.com/RECETOX/MSMetaEnhancer. However, we distribute our library through Conda and that requires all the dependencies to be available via Conda. We'd appreciate if you could publish your library to [Conda-forge](https://conda-forge.org/#page-top). This will also increase its accessibility!

Conda-forge have documented how to publish a package here: 
https://conda-forge.org/docs/maintainer/adding_pkgs.html#contributing-packages

Also since your library is already on PyPi it should be easy to autogenerate a Conda recipe with **grayskull**:
https://github.com/conda-incubator/grayskull

You can check out our library for an example of a Conda recipe:
https://github.com/RECETOX/MSMetaEnhancer/blob/main/conda/meta.yaml

If you need assistance with any of that I'd be happy to help :)

**Comment by xtrojak** [comment]
In progress [here](https://github.com/conda-forge/staged-recipes/pull/20204).

**Comment by xtrojak** [comment]
Package is available on anaconda https://anaconda.org/conda-forge/aiocircuitbreaker, can be closed.
